pub mod delete_confirm;
pub mod format;
pub mod results_grid;
pub mod results_table;
pub mod results_table_similar;
pub mod settings_panel;
pub mod stats_panel;
pub mod status_bar;
pub mod thumbnails;
